version: '3'
services:
  consumer:
    build:
      context: ./RabbitMQ.Consumer
      dockerfile: Dockerfile
    image: consumer
    container_name: container_consumer
    # Otras configuraciones para el servicio del consumidor

  producer:
    build:
      context: ./RabbitMQ.Producer
      dockerfile: Dockerfile
    image: producer
    container_name: container_producer
    # Otras configuraciones para el servicio del productor

